package:
  name: ros-noetic-rosbridge-suite
  version: 0.11.14
source:
  git_url: https://github.com/RobotWebTools-release/rosbridge_suite-release.git
  git_rev: release/noetic/rosbridge_suite/0.11.14-1
  folder: ros-noetic-rosbridge-suite/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 8
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.3 noetic
    - ros-noetic-rosapi
    - ros-noetic-rosbridge-library
    - ros-noetic-rosbridge-server
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
