jobs:
  stage_0_job_0:
    name: rosbridge-library rosbridge-msgs rosapi rosbridge-server
    runs-on:
    - self-hosted
    - linux
    - ARM64
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-noetic-rosbridge-library ros-noetic-rosbridge-msgs ros-noetic-rosapi
        ros-noetic-rosbridge-server
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-noetic-rosbridge-library ros-noetic-rosbridge-msgs ros-noetic-rosapi
          ros-noetic-rosbridge-server
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
  stage_1_job_1:
    name: rosbridge-suite
    runs-on:
    - self-hosted
    - linux
    - ARM64
    strategy:
      fail-fast: false
    needs:
    - stage_0_job_0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build ros-noetic-rosbridge-suite
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-noetic-rosbridge-suite
        DOCKER_IMAGE: condaforge/linux-anvil-aarch64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
on:
  push:
    branches:
    - buildbranch_linux_aarch64
